# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme

locale: en-DE
title: "The NC Journal"
description: "Digital Tranformation and more."
baseurl: # the subpath of your site, e.g. "/blog"
url: https://nanachimi.com
#url: "http://localhost:4000"
logo: "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "G-6J0XWZHD77"
disqus:
  shortname: "nanachimi"
twitter:
  username: "ananachimi"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Nana Chimi
  picture: /images/me.jpg
  email: me@nanachimi.com
  twitter: ananachimi
  links:
    - title: Twitter
      url: https://twitter.com/ananachimi
      icon: fab fa-twitter
    - title: Github
      url: https://github.com/nanachimi
      icon: fab fa-github
    - title: LinkedIn
      url: https://www.linkedin.com/in/nanachimi/
      icon: fab fa-linkedin
      
# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/ananachimi
    icon: fab fa-twitter
  - title: Github
    url: https://github.com/nanachimi
    icon: fab fa-github
  - title: LinkedIn
    url: https://www.linkedin.com/in/nanachimi/
    icon: fab fa-linkedin
